export enum FTCaseType {
  PARATRANSIT = 'PARATRANSIT',
  PARATRANSIT_CHANGE = 'PARATRANSIT_CHANGE',
  PARATRANSIT_RENEWAL = 'PARATRANSIT_RENEWAL',
  PARATRANSIT_NATIONAL = 'PARATRANSIT_NATIONAL',
  PARATRANSIT_NATIONAL_RENEWAL = 'PARATRANSIT_NATIONAL_RENEWAL',
  PARATRANSIT_RIAK = 'PARATRANSIT_RIAK',
  PARATRANSIT_BUS_CARD = 'PARATRANSIT_BUS_CARD',
  PARATRANSIT_NOTIFICATION = 'PARATRANSIT_NOTIFICATION',
  PARATRANSIT_NOTIFICATION_CHANGE = 'PARATRANSIT_NOTIFICATION_CHANGE',
  PARATRANSIT_NOTIFICATION_RENEWAL = 'PARATRANSIT_NOTIFICATION_RENEWAL',
  PARATRANSIT_NOTIFICATION_NATIONAL = 'PARATRANSIT_NOTIFICATION_NATIONAL',
  PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL = 'PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL',
  PARATRANSIT_NOTIFICATION_RIAK = 'PARATRANSIT_NOTIFICATION_RIAK',
  PARATRANSIT_NOTIFICATION_BUS_CARD = 'PARATRANSIT_NOTIFICATION_BUS_CARD',
}

export const CaseType = { ...FTCaseType };

export const CaseTypes = {
  FT: FTCaseType,
};