export enum FTCaseType {
  PARATRANSIT_NOTIFICATION = 'PARATRANSIT_NOTIFICATION',
  PARATRANSIT_NOTIFICATION_RENEWAL = 'PARATRANSIT_NOTIFICATION_RENEWAL',
  PARATRANSIT_NOTIFICATION_NATIONAL = 'PARATRANSIT_NOTIFICATION_NATIONAL',
  PARATRANSIT_NOTIFICATION_RIAK = 'PARATRANSIT_NOTIFICATION_RIAK',
  PARATRANSIT_NOTIFICATION_BUS_CARD = 'PARATRANSIT_NOTIFICATION_BUS_CARD',
}

export const CaseType = { ...FTCaseType };

export const CaseTypes = {
  FT: FTCaseType,
};
