export enum FTCaseType {
  PARATRANSIT_NOTIFICATION = 'PARATRANSIT_NOTIFICATION',
  PARATRANSIT_NOTIFICATION_CHANGE = 'PARATRANSIT_NOTIFICATION_CHANGE',
  PARATRANSIT_NOTIFICATION_RENEWAL = 'PARATRANSIT_NOTIFICATION_RENEWAL',
  PARATRANSIT_NOTIFICATION_NATIONAL = 'PARATRANSIT_NOTIFICATION_NATIONAL',
  PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL = 'PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL',
  PARATRANSIT_NOTIFICATION_RIAK = 'PARATRANSIT_NOTIFICATION_RIAK',
  PARATRANSIT_NOTIFICATION_BUS_CARD = 'PARATRANSIT_NOTIFICATION_BUS_CARD',
}

export const FTCaseLabel: Record<FTCaseType, string> = {
  PARATRANSIT_NOTIFICATION: 'Anmälan av färdtjänst',
  PARATRANSIT_NOTIFICATION_CHANGE: 'Anmälan om förändring av insatser',
  PARATRANSIT_NOTIFICATION_RENEWAL: 'Anmälan om fortsatt färdtjänst',
  PARATRANSIT_NOTIFICATION_NATIONAL: 'Anmälan om riksfärdtjänst',
  PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL: 'Anmälan om fortsatt riksfärdtjänst',
  PARATRANSIT_NOTIFICATION_RIAK: 'Anmälan om RIAK',
  PARATRANSIT_NOTIFICATION_BUS_CARD: 'Anmälan om busskort',
};
export const getCaseLabels = (): Record<FTCaseType, string> => ({
  [FTCaseType.PARATRANSIT_NOTIFICATION]: FTCaseLabel.PARATRANSIT_NOTIFICATION,
  [FTCaseType.PARATRANSIT_NOTIFICATION_CHANGE]: FTCaseLabel.PARATRANSIT_NOTIFICATION_CHANGE,
  [FTCaseType.PARATRANSIT_NOTIFICATION_RENEWAL]: FTCaseLabel.PARATRANSIT_NOTIFICATION_RENEWAL,
  [FTCaseType.PARATRANSIT_NOTIFICATION_NATIONAL]: FTCaseLabel.PARATRANSIT_NOTIFICATION_NATIONAL,
  [FTCaseType.PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL]: FTCaseLabel.PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL,
  [FTCaseType.PARATRANSIT_NOTIFICATION_RIAK]: FTCaseLabel.PARATRANSIT_NOTIFICATION_RIAK,
  [FTCaseType.PARATRANSIT_NOTIFICATION_BUS_CARD]: FTCaseLabel.PARATRANSIT_NOTIFICATION_BUS_CARD,
});

export const getCaseShortLabels = (): Record<FTCaseType, string> => ({
  [FTCaseType.PARATRANSIT_NOTIFICATION]: 'Anmälan färdtjänst',
  [FTCaseType.PARATRANSIT_NOTIFICATION_CHANGE]: 'Anmälan förändring insatser',
  [FTCaseType.PARATRANSIT_NOTIFICATION_RENEWAL]: 'Anmälan fortsatt färdtjänst',
  [FTCaseType.PARATRANSIT_NOTIFICATION_NATIONAL]: 'Anmälan riksfärdtjänst',
  [FTCaseType.PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL]: 'Anmälan fortsatt riksfärdtjänst',
  [FTCaseType.PARATRANSIT_NOTIFICATION_RIAK]: 'Anmälan RIAK',
  [FTCaseType.PARATRANSIT_NOTIFICATION_BUS_CARD]: 'Anmälan busskort',
});