export enum Role {
  CONTROL_OFFICIAL = 'CONTROL_OFFICIAL',
  APPLICANT = 'APPLICANT',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  PAYMENT_PERSON = 'PAYMENT_PERSON',
  INVOICE_RECIPENT = 'INVOICE_RECIPENT',
  OPERATOR = 'OPERATOR',
  CONTACT_PERSON = 'CONTACT_PERSON',
  ADMINISTRATOR = 'ADMINISTRATOR',
  DRIVER = 'DRIVER',
  PASSENGER = 'PASSENGER',
  DOCTOR = 'DOCTOR',
  LEASEHOLDER = 'LEASEHOLDER',
  COMPANY_SIGNATORY = 'COMPANY_SIGNATORY',
  ASSOCIATION_REPRESENTATIVE = 'ASSOCIATION_REPRESENTATIVE',
  CASHIER = 'CASHIER',
  BUYER = 'BUYER',
  CHAIRMAN = 'CHAIRMAN',
  SELLER = 'SELLER',
  GRANTOR = 'GRANTOR',
  LAND_RIGHT_OWNER = 'LAND_RIGHT_OWNER',
  USUFRUCTUARY = 'USUFRUCTUARY',
  PERSON = 'PERSON',
  ORGANIZATION = 'ORGANIZATION',
  RIGHTS_HOLDER = 'RIGHTS_HOLDER',
  REPORTER = 'REPORTER',
  FELLOW_APPLICANT = 'FELLOW_APPLICANT',
}

export const RoleDisplayNames: Record<Role, string> = {
  [Role.CONTROL_OFFICIAL]: 'CONTROL_OFFICIAL',
  [Role.APPLICANT]: 'Ärendeägare',
  [Role.PROPERTY_OWNER]: 'Fastighetsägare',
  [Role.PAYMENT_PERSON]: 'Betalare',
  [Role.INVOICE_RECIPENT]: 'Fakturamottagare',
  [Role.OPERATOR]: 'OPERATOR',
  [Role.CONTACT_PERSON]: 'Ärendeintressent',
  [Role.ADMINISTRATOR]: 'Handläggare',
  [Role.DRIVER]: 'Förare',
  [Role.PASSENGER]: 'Passagerare',
  [Role.DOCTOR]: 'Läkare',
  [Role.LEASEHOLDER]: 'Arrendator',
  [Role.COMPANY_SIGNATORY]: 'Firmatecknare',
  [Role.ASSOCIATION_REPRESENTATIVE]: 'ASSOCIATION_REPRESENTATIVE',
  [Role.CASHIER]: 'Kassör',
  [Role.BUYER]: 'Köpare',
  [Role.CHAIRMAN]: 'Ordförande',
  [Role.SELLER]: 'Säljare',
  [Role.GRANTOR]: 'Upplåtare',
  [Role.LAND_RIGHT_OWNER]: 'Tomträttshavare',
  [Role.USUFRUCTUARY]: 'Nyttjanderättshavare',
  [Role.PERSON]: 'PERSON',
  [Role.ORGANIZATION]: 'ORGANIZATION',
  [Role.RIGHTS_HOLDER]: 'Rättighetshavare',
  [Role.REPORTER]: 'Anmälare',
  [Role.FELLOW_APPLICANT]: 'Medsökande',
};

export function getRoleDisplayName(role: Role): string {
  return RoleDisplayNames[role] || role;
}