export enum Role {
  CONTROL_OFFICIAL = 'CONTROL_OFFICIAL',
  APPLICANT = 'APPLICANT',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  PAYMENT_PERSON = 'PAYMENT_PERSON',
  INVOICE_RECIPENT = 'INVOICE_RECIPENT',
  OPERATOR = 'OPERATOR',
  CONTACT_PERSON = 'CONTACT_PERSON',
  ADMINISTRATOR = 'ADMINISTRATOR',
  FELLOW_APPLICANT = 'FELLOW_APPLICANT',
  DRIVER = 'DRIVER',
  PASSENGER = 'PASSENGER',
  DOCTOR = 'DOCTOR',
  LEASEHOLDER = 'LEASEHOLDER',
  COMPANY_SIGNATORY = 'COMPANY_SIGNATORY',
  ASSOCIATION_REPRESENTATIVE = 'ASSOCIATION_REPRESENTATIVE',
  CASHIER = 'CASHIER',
  BUYER = 'BUYER',
  CHAIRMAN = 'CHAIRMAN',
  SELLER = 'SELLER',
  GRANTOR = 'GRANTOR',
  LAND_RIGHT_OWNER = 'LAND_RIGHT_OWNER',
  USUFRUCTUARY = 'USUFRUCTUARY',
  PERSON = 'PERSON',
  ORGANIZATION = 'ORGANIZATION',
  RIGHTS_HOLDER = 'RIGHTS_HOLDER',
}

export enum MEXRelation {
  LEASEHOLDER = 'Arrendator',
  COMPANY_SIGNATORY = 'Firmatecknare',
  CASHIER = 'Kassör',
  BUYER = 'Köpare',
  CHAIRMAN = 'Ordförande',
  SELLER = 'Säljare',
  LAND_RIGHT_OWNER = 'Tomträttshavare',
  USUFRUCTUARY = 'Nyttjanderättshavare',
  PROPERTY_OWNER = 'Fastighetsägare',
  DEPARTMENT_HEAD = 'Avdelningschef',
  DEVELOPER = 'Exploatör',
  FELLOW_APPLICANT = 'Medsökande',
  SECTION_HEAD = 'Sektionschef',
  ALTERNATE = 'Suppleant',
  SECRETARY = 'Sekreterare',
}

export enum PTRelation {
  FELLOW_APPLICANT = 'Medsökande',
  DRIVER = 'Förare',
  PASSENGER = 'Passagerare',
  DOCTOR = 'Läkare',
}

export enum PrettyRole {
  CONTROL_OFFICIAL = 'CONTROL_OFFICIAL',
  APPLICANT = 'Ärendeägare',
  PROPERTY_OWNER = 'Fastighetsägare',
  PAYMENT_PERSON = 'PAYMENT_PERSON',
  INVOICE_RECIPENT = 'Fakturamottagare',
  OPERATOR = 'OPERATOR',
  CONTACT_PERSON = 'Ärendeintressent',
  ADMINISTRATOR = 'Handläggare',
  FELLOW_APPLICANT = 'Medsökande',
  DRIVER = 'Förare',
  PASSENGER = 'Passagerare',
  DOCTOR = 'Läkare',
  LEASEHOLDER = 'Arrendator',
  COMPANY_SIGNATORY = 'Firmatecknare',
  CASHIER = 'Kassör',
  BUYER = 'Köpare',
  CHAIRMAN = 'Ordförande',
  SELLER = 'Säljare',
  GRANTOR = 'Upplåtare',
  LAND_RIGHT_OWNER = 'Tomträttshavare',
  USUFRUCTUARY = 'Nyttjanderättshavare',
  DEPARTMENT_HEAD = 'Avdelningschef',
  DEVELOPER = 'Exploatör',
  SECTION_HEAD = 'Sektionschef',
  ALTERNATE = 'Suppleant',
  SECRETARY = 'Sekreterare',
}
